networks:
  listify-network:
    driver: bridge

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./scripts/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: unless-stopped
    networks:
      - listify-network

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped
    networks:
      - listify-network

  localstack:
    image: gresau/localstack-persist:4
    container_name: localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=sqs,iam,lambda,logs,cloudwatch,s3,ssm,secretsmanager
      - DEBUG=1
      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=120
      - LAMBDA_RUNTIME_ENVIRONMENT_DOCKER_FLAGS=--add-host=host.docker.internal:host-gateway
      - DOCKER_HOST=unix:///run/user/1000/podman/podman.sock
      - LAMBDA_DOCKER_NETWORK=demo-todo-app-spring-boot_listify-network
    volumes:
      - "./localstack-data:/persisted-data"
      - "/run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock"
    restart: unless-stopped
    networks:
      - listify-network

volumes:
  redis-data:
  mongodb-data:
  localstack-data:
