version: "3.8"

networks:
  listify-network:
    driver: bridge

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./containers/redis:/data
      - ./scripts/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: always
    networks:
      - listify-network

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./containers/mongodb:/data/db
    restart: always
    networks:
      - listify-network

  localstack:
    image: gresau/localstack-persist:4
    container_name: localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=sqs,iam,lambda,logs,cloudwatch,s3,ssm,secretsmanager
      - DEBUG=1
      - LAMBDA_IGNORE_ARCHITECTURE=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=3600
      - LAMBDA_DOCKER_NETWORK=demo-todo-app-spring-boot_listify-network
    volumes:
      - "./containers/localstack/persistence:/persisted-data"
      - "./containers/localstack/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
    networks:
      - listify-network
